.SUFFIXES : .x .o .c .s

CC=hcc
TOP=top
AS=jas
LD=ld
RM=del
GFS=..\utils\applygfs
INC= -I..\\..\\include\\


all     : prog

prog: timelord.o ai.o shot.o \
rdctile.o rpgmap.o actor.o sprhand.o bkgs.o \
sega.o genesis.o utils.o psgsound.o interr.o gfs.o rdc.o \
conio.o string.o plee.o font.o genesisb.o
	$(LD) -b -g -v -o timelord.bin -f objet.inc
	$(GFS) timelord.bin 131072 gamedata.gfs

clean:
	$(RM) *.o
	$(RM) timelord.s
	$(RM) timelord.bin
	$(RM) *.bak

.c.o: 
	@-echo "Making component -> $*.o"
	$(CC) $(INC) $<
	$(TOP) $*.s
	$(AS) $*.s

.s.o:
	@-echo "Making component -> $*.o"
	$(AS) $(CDIR)$*.s


# dependencies -- DO NOT DELETE BELOW THIS LINE -- make depends on it.

timelord.o: timelord.c
ai.o	  : ai.c
shot.o	  : shot.c
bkgs.o	  : bkgs.c
rdctile.o :	rdctile.c
rpgmap.o  :	rpgmap.c
actor.o   :	actor.c
sprhand.o :	sprhand.c
sega.o    : sega.s
genesis.o :	genesis.c
genesisb.o:	genesisb.c
conio.o   :	conio.c
string.o  :	string.c
pleee.o   :	plee.c
utils.o   :	utils.c
psgsound.o:	psgsound.c
interr.o  :	interr.c
gfs.o  	  :	gfs.c
rdc.o  	  :	rdc.c
font.o    : font.c