	.data
L0:
	.dc.b	0
	.dc.b	1
	.dc.b	2
	.dc.b	3
	.dc.b	4
	.dc.b	5
	.dc.b	6
	.dc.b	7
	.dc.b	8
	.dc.b	9
	.dc.b	10
	.dc.b	11
	.dc.b	12
	.dc.b	13
	.dc.b	14
	.dc.b	15
	.dc.b	16
	.dc.b	17
	.dc.b	18
	.dc.b	19
	.dc.b	20
	.dc.b	21
	.dc.b	22
	.dc.b	23
	.dc.b	24
	.dc.b	25
	.dc.b	26
	.dc.b	27
	.dc.b	28
	.dc.b	29
	.dc.b	30
	.dc.b	31
	.dc.b	32
	.dc.b	33
	.dc.b	34
	.dc.b	35
	.dc.b	36
	.dc.b	37
	.dc.b	38
	.dc.b	39
	.dc.b	40
	.dc.b	41
	.dc.b	42
	.dc.b	43
	.dc.b	44
	.dc.b	45
	.dc.b	46
	.dc.b	47
	.dc.b	48
	.dc.b	49
	.dc.b	50
	.dc.b	51
	.dc.b	52
	.dc.b	53
	.dc.b	54
	.dc.b	55
	.dc.b	56
	.dc.b	57
	.dc.b	58
	.dc.b	59
	.dc.b	60
	.dc.b	61
	.dc.b	62
	.dc.b	63
	.dc.b	64
	.dc.b	97
	.dc.b	98
	.dc.b	99
	.dc.b	100
	.dc.b	101
	.dc.b	102
	.dc.b	103
	.dc.b	104
	.dc.b	105
	.dc.b	106
	.dc.b	107
	.dc.b	108
	.dc.b	109
	.dc.b	110
	.dc.b	111
	.dc.b	112
	.dc.b	113
	.dc.b	114
	.dc.b	115
	.dc.b	116
	.dc.b	117
	.dc.b	118
	.dc.b	119
	.dc.b	120
	.dc.b	121
	.dc.b	122
	.dc.b	91
	.dc.b	92
	.dc.b	93
	.dc.b	94
	.dc.b	95
	.dc.b	96
	.dc.b	97
	.dc.b	98
	.dc.b	99
	.dc.b	100
	.dc.b	101
	.dc.b	102
	.dc.b	103
	.dc.b	104
	.dc.b	105
	.dc.b	106
	.dc.b	107
	.dc.b	108
	.dc.b	109
	.dc.b	110
	.dc.b	111
	.dc.b	112
	.dc.b	113
	.dc.b	114
	.dc.b	115
	.dc.b	116
	.dc.b	117
	.dc.b	118
	.dc.b	119
	.dc.b	120
	.dc.b	121
	.dc.b	122
	.dc.b	123
	.dc.b	124
	.dc.b	125
	.dc.b	126
	.dc.b	127
	.dc.b	128
	.dc.b	129
	.dc.b	130
	.dc.b	131
	.dc.b	132
	.dc.b	133
	.dc.b	134
	.dc.b	135
	.dc.b	136
	.dc.b	137
	.dc.b	138
	.dc.b	139
	.dc.b	140
	.dc.b	141
	.dc.b	142
	.dc.b	143
	.dc.b	144
	.dc.b	145
	.dc.b	146
	.dc.b	147
	.dc.b	148
	.dc.b	149
	.dc.b	150
	.dc.b	151
	.dc.b	152
	.dc.b	153
	.dc.b	154
	.dc.b	155
	.dc.b	156
	.dc.b	157
	.dc.b	158
	.dc.b	159
	.dc.b	160
	.dc.b	161
	.dc.b	162
	.dc.b	163
	.dc.b	164
	.dc.b	165
	.dc.b	166
	.dc.b	167
	.dc.b	168
	.dc.b	169
	.dc.b	170
	.dc.b	171
	.dc.b	172
	.dc.b	173
	.dc.b	174
	.dc.b	175
	.dc.b	176
	.dc.b	177
	.dc.b	178
	.dc.b	179
	.dc.b	180
	.dc.b	181
	.dc.b	182
	.dc.b	183
	.dc.b	184
	.dc.b	185
	.dc.b	186
	.dc.b	187
	.dc.b	188
	.dc.b	189
	.dc.b	190
	.dc.b	191
	.dc.b	192
	.dc.b	193
	.dc.b	194
	.dc.b	195
	.dc.b	196
	.dc.b	197
	.dc.b	198
	.dc.b	199
	.dc.b	200
	.dc.b	201
	.dc.b	202
	.dc.b	203
	.dc.b	204
	.dc.b	205
	.dc.b	206
	.dc.b	207
	.dc.b	208
	.dc.b	209
	.dc.b	210
	.dc.b	211
	.dc.b	212
	.dc.b	213
	.dc.b	214
	.dc.b	215
	.dc.b	216
	.dc.b	217
	.dc.b	218
	.dc.b	219
	.dc.b	220
	.dc.b	221
	.dc.b	222
	.dc.b	223
	.dc.b	224
	.dc.b	225
	.dc.b	226
	.dc.b	227
	.dc.b	228
	.dc.b	229
	.dc.b	230
	.dc.b	231
	.dc.b	232
	.dc.b	233
	.dc.b	234
	.dc.b	235
	.dc.b	236
	.dc.b	237
	.dc.b	238
	.dc.b	239
	.dc.b	240
	.dc.b	241
	.dc.b	242
	.dc.b	243
	.dc.b	244
	.dc.b	245
	.dc.b	246
	.dc.b	247
	.dc.b	248
	.dc.b	249
	.dc.b	250
	.dc.b	251
	.dc.b	252
	.dc.b	253
	.dc.b	254
	.dc.b	255
	.text
	.globl	_strcat
_strcat:
	link	a6,#-44
	movem.l	d3/d4/d5/d6,-(sp)
	move.l	12(a6),d6
	move.l	8(a6),d5
	moveq.l	#0,d3
L4:
	move.l	d5,-(sp)
	jsr	_strlen
	addq.w	#4,sp
	move.w	d3,d1
	cmp.w	d0,d1
	bcc	L6
	moveq.l	#0,d0
	move.w	d3,d0
	add.l	d5,d0
	move.l	d0,a0
	moveq.l	#0,d0
	move.w	d3,d0
	move.b	(a0),-40(a6,d0.l)
	addq.w	#1,d3
	bra	L4
L6:
	moveq.l	#0,d4
L7:
	move.l	d6,-(sp)
	jsr	_strlen
	addq.w	#4,sp
	move.w	d4,d1
	cmp.w	d0,d1
	bcc	L9
	moveq.l	#0,d0
	move.w	d3,d0
	add.l	d6,d0
	move.l	d0,a0
	move.w	d4,d0
	add.w	d3,d0
	moveq.l	#0,d1
	move.w	d0,d1
	move.b	(a0),-40(a6,d1.l)
	addq.w	#1,d4
	bra	L7
L9:
	lea	-40(a6),a0
	move.l	a0,d0
	movem.l	(sp)+,d3/d4/d5/d6
	unlk	a6
	rts
	.text
	.globl	_strcpy
_strcpy:
	link	a6,#-2
	movem.l	d3/d4/d5,-(sp)
	move.l	12(a6),d5
	move.l	8(a6),d4
	moveq.l	#0,d3
L13:
	move.l	d5,-(sp)
	jsr	_strlen
	addq.w	#4,sp
	move.w	d3,d1
	cmp.w	d0,d1
	bcc	L15
	moveq.l	#0,d0
	move.w	d3,d0
	add.l	d5,d0
	move.l	d0,a0
	moveq.l	#0,d0
	move.w	d3,d0
	add.l	d4,d0
	move.l	d0,a1
	move.b	(a0),(a1)
	addq.w	#1,d3
	bra	L13
L15:
	move.l	d4,d0
	movem.l	(sp)+,d3/d4/d5
	unlk	a6
	rts
	.text
	.globl	_strlen
_strlen:
	link	a6,#0
	movem.l	d3/a3,-(sp)
	move.l	8(a6),d3
	move.l	d3,a3
L19:
	tst.b	(a3)
	beq	L21
	addq.l	#1,a3
	bra	L19
L21:
	move.l	a3,d0
	sub.l	d3,d0
	movem.l	(sp)+,d3/a3
	unlk	a6
	rts
	.text
	.globl	_strchr
_strchr:
	link	a6,#0
L25:
	move.l	8(a6),a0
	tst.b	(a0)
	beq	L26
	move.l	8(a6),a0
	move.b	(a0),d0
	ext.w	d0
	cmp.w	12(a6),d0
	bne	L27
	move.l	8(a6),d0
L24:
	unlk	a6
	rts
L27:
	addq.l	#1,8(a6)
	bra	L25
L26:
	tst.w	12(a6)
	bne	L28
	move.l	8(a6),d0
	bra	L24
L28:
	moveq.l	#0,d0
	bra	L24
	.text
	.globl	_strcmp
_strcmp:
	link	a6,#0
L32:
	move.l	12(a6),a0
	addq.l	#1,12(a6)
	move.l	8(a6),a1
	move.b	(a1),d0
	cmp.b	(a0),d0
	bne	L33
	move.l	8(a6),a0
	addq.l	#1,8(a6)
	tst.b	(a0)
	bne	L32
	clr.w	d0
L31:
	unlk	a6
	rts
L33:
	move.l	8(a6),a0
	clr.w	d0
	move.b	(a0),d0
	subq.l	#1,12(a6)
	move.l	12(a6),a0
	clr.w	d1
	move.b	(a0),d1
	sub.w	d1,d0
	bra	L31
	.text
	.globl	_strncat
_strncat:
	link	a6,#-8
	movem.l	d3/d4/d5/d6,-(sp)
	move.l	8(a6),d6
	move.w	16(a6),d4
	move.l	d6,d3
	move.l	12(a6),d5
	tst.w	d4
	beq	L38
L39:
	move.l	d3,a0
	tst.b	(a0)
	beq	L41
	addq.l	#1,d3
	bra	L39
L41:
	move.l	d5,d0
	addq.l	#1,d5
	move.l	d0,a0
	move.l	d3,a1
	move.b	(a0),(a1)
	bne	L44
L43:
	move.l	d3,a0
	move.b	#0,(a0)
L38:
	move.l	d6,d0
	movem.l	(sp)+,d3/d4/d5/d6
	unlk	a6
	rts
L44:
	addq.l	#1,d3
	subq.w	#1,d4
	tst.w	d4
	bne	L41
	bra	L43
	.text
	.globl	_strncmp
_strncmp:
	link	a6,#0
	tst.w	16(a6)
	bne	L49
	clr.w	d0
L47:
	unlk	a6
	rts
L49:
	move.l	12(a6),a0
	addq.l	#1,12(a6)
	move.l	8(a6),a1
	move.b	(a1),d0
	cmp.b	(a0),d0
	beq	L52
	move.l	8(a6),a0
	clr.w	d0
	move.b	(a0),d0
	subq.l	#1,12(a6)
	move.l	12(a6),a0
	clr.w	d1
	move.b	(a0),d1
	sub.w	d1,d0
	bra	L47
L52:
	move.l	8(a6),a0
	addq.l	#1,8(a6)
	tst.b	(a0)
	bne	L50
L51:
	clr.w	d0
	bra	L47
L50:
	subq.w	#1,16(a6)
	tst.w	16(a6)
	bne	L49
	bra	L51
	.text
	.globl	_strncpy
_strncpy:
	link	a6,#-8
	movem.l	d3/d4/d5,-(sp)
	move.l	8(a6),d5
	move.l	d5,d3
	move.l	12(a6),d4
	tst.w	16(a6)
	beq	L57
L58:
	move.l	d4,d0
	addq.l	#1,d4
	move.l	d0,a0
	move.l	d3,d0
	addq.l	#1,d3
	move.l	d0,a1
	move.b	(a0),(a1)
	bne	L59
L62:
	subq.w	#1,16(a6)
	tst.w	16(a6)
	beq	L57
	move.l	d3,d0
	addq.l	#1,d3
	move.l	d0,a0
	move.b	#0,(a0)
	bra	L62
L57:
	move.l	d5,d0
	movem.l	(sp)+,d3/d4/d5
	unlk	a6
	rts
L59:
	subq.w	#1,16(a6)
	tst.w	16(a6)
	bne	L58
	bra	L57
	.text
	.globl	_strpbrk
_strpbrk:
	link	a6,#-8
L67:
	move.l	8(a6),a0
	addq.l	#1,8(a6)
	move.b	(a0),d0
	ext.w	d0
	move.w	d0,-6(a6)
	beq	L68
	move.l	12(a6),-4(a6)
L69:
	move.l	-4(a6),a0
	addq.l	#1,-4(a6)
	move.b	(a0),d0
	ext.w	d0
	move.w	d0,-8(a6)
	beq	L67
	move.w	-8(a6),d0
	cmp.w	-6(a6),d0
	bne	L69
	move.l	8(a6),d0
	subq.l	#1,d0
L66:
	unlk	a6
	rts
L68:
	moveq.l	#0,d0
	bra	L66
	.text
	.globl	_strtok
_strtok:
	link	a6,#-8
	movem.l	d3/d4/d5/d6/d7/a3,-(sp)
	move.l	12(a6),d7
	move.l	8(a6),d5
	tst.l	d5
	bne	L77
	move.l	d6,d5
	bne	L77
	moveq.l	#0,d0
L75:
	movem.l	(sp)+,d3/d4/d5/d6/d7/a3
	unlk	a6
	rts
L77:
	move.l	d5,a0
	addq.l	#1,d5
	move.b	(a0),d3
	ext.w	d3
	move.l	d7,a3
L78:
	move.b	(a3)+,d4
	ext.w	d4
	beq	L80
	cmp.w	d4,d3
	bne	L78
	bra	L77
L80:
	tst.w	d3
	bne	L82
	moveq.l	#0,d6
	moveq.l	#0,d0
	bra	L75
L82:
	move.l	d5,d0
	subq.l	#1,d0
	move.l	d0,-4(a6)
L83:
	move.l	d5,a0
	addq.l	#1,d5
	move.b	(a0),d3
	ext.w	d3
	move.l	d7,a3
L86:
	move.b	(a3)+,d4
	ext.w	d4
	cmp.w	d3,d4
	bne	L87
	tst.w	d3
	bne	L90
	moveq.l	#0,d5
L91:
	move.l	d5,d6
	move.l	-4(a6),d0
	bra	L75
L90:
	move.l	d5,a0
	move.b	#0,-1(a0)
	bra	L91
L87:
	tst.w	d4
	bne	L86
	bra	L83
	.text
	.globl	_strsep
_strsep:
	link	a6,#-4
	movem.l	d3/d4/d5/d6/a3/a4,-(sp)
	move.l	8(a6),d5
	move.l	d5,a0
	move.l	(a0),a3
	cmp.l	#0,a3
	bne	L95
	moveq.l	#0,d0
L94:
	movem.l	(sp)+,d3/d4/d5/d6/a3/a4
	unlk	a6
	rts
L95:
	move.l	a3,d6
L96:
	move.b	(a3)+,d3
	ext.w	d3
	move.l	12(a6),a4
L99:
	move.b	(a4)+,d4
	ext.w	d4
	cmp.w	d3,d4
	bne	L100
	tst.w	d3
	bne	L103
	sub.l	a3,a3
L104:
	move.l	d5,a0
	move.l	a3,(a0)
	move.l	d6,d0
	bra	L94
L103:
	move.b	#0,-1(a3)
	bra	L104
L100:
	tst.w	d4
	bne	L99
	bra	L96
	.text
	.globl	_strlwr
_strlwr:
	link	a6,#-4
	movem.l	d3/d4,-(sp)
	move.l	8(a6),d3
	move.l	d3,d4
L108:
	move.l	d3,a0
	tst.b	(a0)
	beq	L109
	move.l	d3,a0
	cmp.b	#65,(a0)
	blt	L110
	move.l	d3,a0
	cmp.b	#90,(a0)
	bgt	L110
	move.l	d3,a0
	add.b	#32,(a0)
L110:
	addq.l	#1,d3
	bra	L108
L109:
	move.l	d4,d0
	movem.l	(sp)+,d3/d4
	unlk	a6
	rts
	.text
	.globl	_strupr
_strupr:
	link	a6,#-4
	movem.l	d3/d4,-(sp)
	move.l	8(a6),d3
	move.l	d3,d4
L114:
	move.l	d3,a0
	tst.b	(a0)
	beq	L115
	move.l	d3,a0
	cmp.b	#97,(a0)
	blt	L116
	move.l	d3,a0
	cmp.b	#122,(a0)
	bgt	L116
	move.l	d3,a0
	add.b	#-32,(a0)
L116:
	addq.l	#1,d3
	bra	L114
L115:
	move.l	d4,d0
	movem.l	(sp)+,d3/d4
	unlk	a6
	rts
	.text
	.globl	_strcasecmp
_strcasecmp:
	link	a6,#0
	movem.l	a3-a5,-(sp)
	move.l	#L0,a3
	move.l	8(a6),a4
	move.l	12(a6),a5
L120:
	moveq.l	#0,d0
	move.b	(a4),d0
	lea	0(a3,d0.l),a0
	moveq.l	#0,d0
	move.b	(a5)+,d0
	lea	0(a3,d0.l),a1
	move.b	(a0),d0
	cmp.b	(a1),d0
	bne	L121
	tst.b	(a4)+
	bne	L120
	clr.w	d0
L119:
	movem.l	(sp)+,a3-a5
	unlk	a6
	rts
L121:
	moveq.l	#0,d0
	move.b	(a4),d0
	lea	0(a3,d0.l),a0
	clr.w	d0
	move.b	(a0),d0
	subq.l	#1,a5
	moveq.l	#0,d1
	move.b	(a5),d1
	lea	0(a3,d1.l),a0
	clr.w	d1
	move.b	(a0),d1
	sub.w	d1,d0
	bra	L119
	.data
	.text
	.globl	_strncasecmp
_strncasecmp:
	link	a6,#0
	movem.l	d3/a3/a4/a5,-(sp)
	move.w	16(a6),d3
	tst.w	d3
	beq	L126
	move.l	#L0,a3
	move.l	8(a6),a4
	move.l	12(a6),a5
L127:
	moveq.l	#0,d0
	move.b	(a4),d0
	lea	0(a3,d0.l),a0
	moveq.l	#0,d0
	move.b	(a5)+,d0
	lea	0(a3,d0.l),a1
	move.b	(a0),d0
	cmp.b	(a1),d0
	beq	L130
	moveq.l	#0,d0
	move.b	(a4),d0
	lea	0(a3,d0.l),a0
	clr.w	d0
	move.b	(a0),d0
	subq.l	#1,a5
	moveq.l	#0,d1
	move.b	(a5),d1
	lea	0(a3,d1.l),a0
	clr.w	d1
	move.b	(a0),d1
	sub.w	d1,d0
L125:
	movem.l	(sp)+,d3/a3/a4/a5
	unlk	a6
	rts
L130:
	tst.b	(a4)+
	bne	L128
L126:
	clr.w	d0
	bra	L125
L128:
	subq.w	#1,d3
	tst.w	d3
	bne	L127
	bra	L126
