call conv intro3
call conv intro4
call conv intro5
call conv select
call conv select0
call conv spewm
call conv spews
call conv table2
call conv taunt
call conv taunta
call conv tauntb
call conv winner1
call conv winner2
call conv winner3
call conv winner4
call conv winner5
call conv zone1
call conv zone2
call conv zone2S
call conv zone3
call conv zone3S
call conv zone4
call conv zone5
call conv zone6
call conv zone7
call conv zone8
call conv bluebio
call conv greenbio
call conv redbio
call conv yellbio
call conv purpbio

pcx2gens paddles.pcx paddles.til 2 
rdc c paddles.rdc paddles.til

move *.rdc ..\data
move *.map ..\data
move *.h ..\pal
