_scale_table:
; Escala 1
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	1	; Altura
	.db	255	; Passo
	.dw	96	; Offset inicial
; Escala 2
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	2	; Altura
	.db	255	; Passo
	.dw	94	; Offset inicial
; Escala 3
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	3	; Altura
	.db	255	; Passo
	.dw	94	; Offset inicial
; Escala 4
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	4	; Altura
	.db	255	; Passo
	.dw	92	; Offset inicial
; Escala 5
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	5	; Altura
	.db	255	; Passo
	.dw	92	; Offset inicial
; Escala 6
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	6	; Altura
	.db	255	; Passo
	.dw	90	; Offset inicial
; Escala 7
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	7	; Altura
	.db	255	; Passo
	.dw	90	; Offset inicial
; Escala 8
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	8	; Altura
	.db	255	; Passo
	.dw	88	; Offset inicial
; Escala 9
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	9	; Altura
	.db	227	; Passo
	.dw	88	; Offset inicial
; Escala 10
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	10	; Altura
	.db	204	; Passo
	.dw	86	; Offset inicial
; Escala 11
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	11	; Altura
	.db	186	; Passo
	.dw	86	; Offset inicial
; Escala 12
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	12	; Altura
	.db	170	; Passo
	.dw	84	; Offset inicial
; Escala 13
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	13	; Altura
	.db	157	; Passo
	.dw	84	; Offset inicial
; Escala 14
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	14	; Altura
	.db	146	; Passo
	.dw	82	; Offset inicial
; Escala 15
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	15	; Altura
	.db	136	; Passo
	.dw	82	; Offset inicial
; Escala 16
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	16	; Altura
	.db	128	; Passo
	.dw	80	; Offset inicial
; Escala 17
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	17	; Altura
	.db	120	; Passo
	.dw	80	; Offset inicial
; Escala 18
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	18	; Altura
	.db	113	; Passo
	.dw	78	; Offset inicial
; Escala 19
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	19	; Altura
	.db	107	; Passo
	.dw	78	; Offset inicial
; Escala 20
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	20	; Altura
	.db	102	; Passo
	.dw	76	; Offset inicial
; Escala 21
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	21	; Altura
	.db	97	; Passo
	.dw	76	; Offset inicial
; Escala 22
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	22	; Altura
	.db	93	; Passo
	.dw	74	; Offset inicial
; Escala 23
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	23	; Altura
	.db	89	; Passo
	.dw	74	; Offset inicial
; Escala 24
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	24	; Altura
	.db	85	; Passo
	.dw	72	; Offset inicial
; Escala 25
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	25	; Altura
	.db	81	; Passo
	.dw	72	; Offset inicial
; Escala 26
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	26	; Altura
	.db	78	; Passo
	.dw	70	; Offset inicial
; Escala 27
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	27	; Altura
	.db	75	; Passo
	.dw	70	; Offset inicial
; Escala 28
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	28	; Altura
	.db	73	; Passo
	.dw	68	; Offset inicial
; Escala 29
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	29	; Altura
	.db	70	; Passo
	.dw	68	; Offset inicial
; Escala 30
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	30	; Altura
	.db	68	; Passo
	.dw	66	; Offset inicial
; Escala 31
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	31	; Altura
	.db	66	; Passo
	.dw	66	; Offset inicial
; Escala 32
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	32	; Altura
	.db	64	; Passo
	.dw	64	; Offset inicial
; Escala 33
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	33	; Altura
	.db	62	; Passo
	.dw	64	; Offset inicial
; Escala 34
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	34	; Altura
	.db	60	; Passo
	.dw	62	; Offset inicial
; Escala 35
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	35	; Altura
	.db	58	; Passo
	.dw	62	; Offset inicial
; Escala 36
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	36	; Altura
	.db	56	; Passo
	.dw	60	; Offset inicial
; Escala 37
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	37	; Altura
	.db	55	; Passo
	.dw	60	; Offset inicial
; Escala 38
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	38	; Altura
	.db	53	; Passo
	.dw	58	; Offset inicial
; Escala 39
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	39	; Altura
	.db	52	; Passo
	.dw	58	; Offset inicial
; Escala 40
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	40	; Altura
	.db	51	; Passo
	.dw	56	; Offset inicial
; Escala 41
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	41	; Altura
	.db	49	; Passo
	.dw	56	; Offset inicial
; Escala 42
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	42	; Altura
	.db	48	; Passo
	.dw	54	; Offset inicial
; Escala 43
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	43	; Altura
	.db	47	; Passo
	.dw	54	; Offset inicial
; Escala 44
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	44	; Altura
	.db	46	; Passo
	.dw	52	; Offset inicial
; Escala 45
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	45	; Altura
	.db	45	; Passo
	.dw	52	; Offset inicial
; Escala 46
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	46	; Altura
	.db	44	; Passo
	.dw	50	; Offset inicial
; Escala 47
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	47	; Altura
	.db	43	; Passo
	.dw	50	; Offset inicial
; Escala 48
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	48	; Altura
	.db	42	; Passo
	.dw	48	; Offset inicial
; Escala 49
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	49	; Altura
	.db	41	; Passo
	.dw	48	; Offset inicial
; Escala 50
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	50	; Altura
	.db	40	; Passo
	.dw	46	; Offset inicial
; Escala 51
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	51	; Altura
	.db	40	; Passo
	.dw	46	; Offset inicial
; Escala 52
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	52	; Altura
	.db	39	; Passo
	.dw	44	; Offset inicial
; Escala 53
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	53	; Altura
	.db	38	; Passo
	.dw	44	; Offset inicial
; Escala 54
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	54	; Altura
	.db	37	; Passo
	.dw	42	; Offset inicial
; Escala 55
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	55	; Altura
	.db	37	; Passo
	.dw	42	; Offset inicial
; Escala 56
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	56	; Altura
	.db	36	; Passo
	.dw	40	; Offset inicial
; Escala 57
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	57	; Altura
	.db	35	; Passo
	.dw	40	; Offset inicial
; Escala 58
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	58	; Altura
	.db	35	; Passo
	.dw	38	; Offset inicial
; Escala 59
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	59	; Altura
	.db	34	; Passo
	.dw	38	; Offset inicial
; Escala 60
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	60	; Altura
	.db	34	; Passo
	.dw	36	; Offset inicial
; Escala 61
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	61	; Altura
	.db	33	; Passo
	.dw	36	; Offset inicial
; Escala 62
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	62	; Altura
	.db	33	; Passo
	.dw	34	; Offset inicial
; Escala 63
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	63	; Altura
	.db	32	; Passo
	.dw	34	; Offset inicial
; Escala 64
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	64	; Altura
	.db	32	; Passo
	.dw	32	; Offset inicial
; Escala 65
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	65	; Altura
	.db	31	; Passo
	.dw	32	; Offset inicial
; Escala 66
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	66	; Altura
	.db	31	; Passo
	.dw	30	; Offset inicial
; Escala 67
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	67	; Altura
	.db	30	; Passo
	.dw	30	; Offset inicial
; Escala 68
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	68	; Altura
	.db	30	; Passo
	.dw	28	; Offset inicial
; Escala 69
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	69	; Altura
	.db	29	; Passo
	.dw	28	; Offset inicial
; Escala 70
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	70	; Altura
	.db	29	; Passo
	.dw	26	; Offset inicial
; Escala 71
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	71	; Altura
	.db	28	; Passo
	.dw	26	; Offset inicial
; Escala 72
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	72	; Altura
	.db	28	; Passo
	.dw	24	; Offset inicial
; Escala 73
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	73	; Altura
	.db	28	; Passo
	.dw	24	; Offset inicial
; Escala 74
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	74	; Altura
	.db	27	; Passo
	.dw	22	; Offset inicial
; Escala 75
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	75	; Altura
	.db	27	; Passo
	.dw	22	; Offset inicial
; Escala 76
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	76	; Altura
	.db	26	; Passo
	.dw	20	; Offset inicial
; Escala 77
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	77	; Altura
	.db	26	; Passo
	.dw	20	; Offset inicial
; Escala 78
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	78	; Altura
	.db	26	; Passo
	.dw	18	; Offset inicial
; Escala 79
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	79	; Altura
	.db	25	; Passo
	.dw	18	; Offset inicial
; Escala 80
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	80	; Altura
	.db	25	; Passo
	.dw	16	; Offset inicial
; Escala 81
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	81	; Altura
	.db	25	; Passo
	.dw	16	; Offset inicial
; Escala 82
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	82	; Altura
	.db	24	; Passo
	.dw	14	; Offset inicial
; Escala 83
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	83	; Altura
	.db	24	; Passo
	.dw	14	; Offset inicial
; Escala 84
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	84	; Altura
	.db	24	; Passo
	.dw	12	; Offset inicial
; Escala 85
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	85	; Altura
	.db	24	; Passo
	.dw	12	; Offset inicial
; Escala 86
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	86	; Altura
	.db	23	; Passo
	.dw	10	; Offset inicial
; Escala 87
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	87	; Altura
	.db	23	; Passo
	.dw	10	; Offset inicial
; Escala 88
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	88	; Altura
	.db	23	; Passo
	.dw	8	; Offset inicial
; Escala 89
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	89	; Altura
	.db	23	; Passo
	.dw	8	; Offset inicial
; Escala 90
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	90	; Altura
	.db	22	; Passo
	.dw	6	; Offset inicial
; Escala 91
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	91	; Altura
	.db	22	; Passo
	.dw	6	; Offset inicial
; Escala 92
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	92	; Altura
	.db	22	; Passo
	.dw	4	; Offset inicial
; Escala 93
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	93	; Altura
	.db	22	; Passo
	.dw	4	; Offset inicial
; Escala 94
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	94	; Altura
	.db	21	; Passo
	.dw	2	; Offset inicial
; Escala 95
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	95	; Altura
	.db	21	; Passo
	.dw	2	; Offset inicial
; Escala 96
	.db	0	; Passo inicial
	.db	0	; Shift inicial
	.db	96	; Altura
	.db	21	; Passo
	.dw	0	; Offset inicial
; Escala 97
	.db	10	; Passo inicial
	.db	0	; Shift inicial
	.db	96	; Altura
	.db	21	; Passo
	.dw	0	; Offset inicial
; Escala 98
	.db	20	; Passo inicial
	.db	0	; Shift inicial
	.db	96	; Altura
	.db	20	; Passo
	.dw	0	; Offset inicial
; Escala 99
	.db	31	; Passo inicial
	.db	0	; Shift inicial
	.db	96	; Altura
	.db	20	; Passo
	.dw	0	; Offset inicial
; Escala 100
	.db	40	; Passo inicial
	.db	0	; Shift inicial
	.db	96	; Altura
	.db	20	; Passo
	.dw	0	; Offset inicial
; Escala 101
	.db	50	; Passo inicial
	.db	0	; Shift inicial
	.db	96	; Altura
	.db	20	; Passo
	.dw	0	; Offset inicial
; Escala 102
	.db	60	; Passo inicial
	.db	0	; Shift inicial
	.db	96	; Altura
	.db	20	; Passo
	.dw	0	; Offset inicial
; Escala 103
	.db	69	; Passo inicial
	.db	0	; Shift inicial
	.db	96	; Altura
	.db	19	; Passo
	.dw	0	; Offset inicial
; Escala 104
	.db	78	; Passo inicial
	.db	0	; Shift inicial
	.db	96	; Altura
	.db	19	; Passo
	.dw	0	; Offset inicial
; Escala 105
	.db	87	; Passo inicial
	.db	0	; Shift inicial
	.db	96	; Altura
	.db	19	; Passo
	.dw	0	; Offset inicial
; Escala 106
	.db	96	; Passo inicial
	.db	0	; Shift inicial
	.db	96	; Altura
	.db	19	; Passo
	.dw	0	; Offset inicial
; Escala 107
	.db	105	; Passo inicial
	.db	0	; Shift inicial
	.db	96	; Altura
	.db	19	; Passo
	.dw	0	; Offset inicial
; Escala 108
	.db	113	; Passo inicial
	.db	0	; Shift inicial
	.db	96	; Altura
	.db	18	; Passo
	.dw	0	; Offset inicial
; Escala 109
	.db	122	; Passo inicial
	.db	0	; Shift inicial
	.db	96	; Altura
	.db	18	; Passo
	.dw	0	; Offset inicial
; Escala 110
	.db	130	; Passo inicial
	.db	0	; Shift inicial
	.db	96	; Altura
	.db	18	; Passo
	.dw	0	; Offset inicial
; Escala 111
	.db	138	; Passo inicial
	.db	0	; Shift inicial
	.db	96	; Altura
	.db	18	; Passo
	.dw	0	; Offset inicial
; Escala 112
	.db	146	; Passo inicial
	.db	0	; Shift inicial
	.db	96	; Altura
	.db	18	; Passo
	.dw	0	; Offset inicial
; Escala 113
	.db	154	; Passo inicial
	.db	0	; Shift inicial
	.db	96	; Altura
	.db	18	; Passo
	.dw	0	; Offset inicial
; Escala 114
	.db	161	; Passo inicial
	.db	0	; Shift inicial
	.db	96	; Altura
	.db	17	; Passo
	.dw	0	; Offset inicial
; Escala 115
	.db	169	; Passo inicial
	.db	0	; Shift inicial
	.db	96	; Altura
	.db	17	; Passo
	.dw	0	; Offset inicial
; Escala 116
	.db	176	; Passo inicial
	.db	0	; Shift inicial
	.db	96	; Altura
	.db	17	; Passo
	.dw	0	; Offset inicial
; Escala 117
	.db	183	; Passo inicial
	.db	0	; Shift inicial
	.db	96	; Altura
	.db	17	; Passo
	.dw	0	; Offset inicial
; Escala 118
	.db	190	; Passo inicial
	.db	0	; Shift inicial
	.db	96	; Altura
	.db	17	; Passo
	.dw	0	; Offset inicial
; Escala 119
	.db	197	; Passo inicial
	.db	0	; Shift inicial
	.db	96	; Altura
	.db	17	; Passo
	.dw	0	; Offset inicial
; Escala 120
	.db	204	; Passo inicial
	.db	0	; Shift inicial
	.db	96	; Altura
	.db	17	; Passo
	.dw	0	; Offset inicial
; Escala 121
	.db	211	; Passo inicial
	.db	0	; Shift inicial
	.db	96	; Altura
	.db	16	; Passo
	.dw	0	; Offset inicial
; Escala 122
	.db	218	; Passo inicial
	.db	0	; Shift inicial
	.db	96	; Altura
	.db	16	; Passo
	.dw	0	; Offset inicial
; Escala 123
	.db	224	; Passo inicial
	.db	0	; Shift inicial
	.db	96	; Altura
	.db	16	; Passo
	.dw	0	; Offset inicial
; Escala 124
	.db	231	; Passo inicial
	.db	0	; Shift inicial
	.db	96	; Altura
	.db	16	; Passo
	.dw	0	; Offset inicial
; Escala 125
	.db	237	; Passo inicial
	.db	0	; Shift inicial
	.db	96	; Altura
	.db	16	; Passo
	.dw	0	; Offset inicial
; Escala 126
	.db	243	; Passo inicial
	.db	0	; Shift inicial
	.db	96	; Altura
	.db	16	; Passo
	.dw	0	; Offset inicial
; Escala 127
	.db	249	; Passo inicial
	.db	0	; Shift inicial
	.db	96	; Altura
	.db	16	; Passo
	.dw	0	; Offset inicial
; Escala 128
	.db	0	; Passo inicial
	.db	1	; Shift inicial
	.db	96	; Altura
	.db	16	; Passo
	.dw	0	; Offset inicial
; Escala 129
	.db	5	; Passo inicial
	.db	1	; Shift inicial
	.db	96	; Altura
	.db	15	; Passo
	.dw	0	; Offset inicial
; Escala 130
	.db	11	; Passo inicial
	.db	1	; Shift inicial
	.db	96	; Altura
	.db	15	; Passo
	.dw	0	; Offset inicial
; Escala 131
	.db	17	; Passo inicial
	.db	1	; Shift inicial
	.db	96	; Altura
	.db	15	; Passo
	.dw	0	; Offset inicial
; Escala 132
	.db	23	; Passo inicial
	.db	1	; Shift inicial
	.db	96	; Altura
	.db	15	; Passo
	.dw	0	; Offset inicial
; Escala 133
	.db	28	; Passo inicial
	.db	1	; Shift inicial
	.db	96	; Altura
	.db	15	; Passo
	.dw	0	; Offset inicial
; Escala 134
	.db	34	; Passo inicial
	.db	1	; Shift inicial
	.db	96	; Altura
	.db	15	; Passo
	.dw	0	; Offset inicial
; Escala 135
	.db	39	; Passo inicial
	.db	1	; Shift inicial
	.db	96	; Altura
	.db	15	; Passo
	.dw	0	; Offset inicial
; Escala 136
	.db	45	; Passo inicial
	.db	1	; Shift inicial
	.db	96	; Altura
	.db	15	; Passo
	.dw	0	; Offset inicial
; Escala 137
	.db	50	; Passo inicial
	.db	1	; Shift inicial
	.db	96	; Altura
	.db	14	; Passo
	.dw	0	; Offset inicial
; Escala 138
	.db	55	; Passo inicial
	.db	1	; Shift inicial
	.db	96	; Altura
	.db	14	; Passo
	.dw	0	; Offset inicial
; Escala 139
	.db	60	; Passo inicial
	.db	1	; Shift inicial
	.db	96	; Altura
	.db	14	; Passo
	.dw	0	; Offset inicial
; Escala 140
	.db	65	; Passo inicial
	.db	1	; Shift inicial
	.db	96	; Altura
	.db	14	; Passo
	.dw	0	; Offset inicial
; Escala 141
	.db	70	; Passo inicial
	.db	1	; Shift inicial
	.db	96	; Altura
	.db	14	; Passo
	.dw	0	; Offset inicial
; Escala 142
	.db	75	; Passo inicial
	.db	1	; Shift inicial
	.db	96	; Altura
	.db	14	; Passo
	.dw	0	; Offset inicial
; Escala 143
	.db	80	; Passo inicial
	.db	1	; Shift inicial
	.db	96	; Altura
	.db	14	; Passo
	.dw	0	; Offset inicial
; Escala 144
	.db	85	; Passo inicial
	.db	1	; Shift inicial
	.db	96	; Altura
	.db	14	; Passo
	.dw	0	; Offset inicial
; Escala 145
	.db	90	; Passo inicial
	.db	1	; Shift inicial
	.db	96	; Altura
	.db	14	; Passo
	.dw	0	; Offset inicial
; Escala 146
	.db	94	; Passo inicial
	.db	1	; Shift inicial
	.db	96	; Altura
	.db	14	; Passo
	.dw	0	; Offset inicial
; Escala 147
	.db	99	; Passo inicial
	.db	1	; Shift inicial
	.db	96	; Altura
	.db	13	; Passo
	.dw	0	; Offset inicial
; Escala 148
	.db	103	; Passo inicial
	.db	1	; Shift inicial
	.db	96	; Altura
	.db	13	; Passo
	.dw	0	; Offset inicial
; Escala 149
	.db	108	; Passo inicial
	.db	1	; Shift inicial
	.db	96	; Altura
	.db	13	; Passo
	.dw	0	; Offset inicial
; Escala 150
	.db	112	; Passo inicial
	.db	1	; Shift inicial
	.db	96	; Altura
	.db	13	; Passo
	.dw	0	; Offset inicial
; Escala 151
	.db	116	; Passo inicial
	.db	1	; Shift inicial
	.db	96	; Altura
	.db	13	; Passo
	.dw	0	; Offset inicial
; Escala 152
	.db	121	; Passo inicial
	.db	1	; Shift inicial
	.db	96	; Altura
	.db	13	; Passo
	.dw	0	; Offset inicial
; Escala 153
	.db	125	; Passo inicial
	.db	1	; Shift inicial
	.db	96	; Altura
	.db	13	; Passo
	.dw	0	; Offset inicial
; Escala 154
	.db	129	; Passo inicial
	.db	1	; Shift inicial
	.db	96	; Altura
	.db	13	; Passo
	.dw	0	; Offset inicial
; Escala 155
	.db	133	; Passo inicial
	.db	1	; Shift inicial
	.db	96	; Altura
	.db	13	; Passo
	.dw	0	; Offset inicial
; Escala 156
	.db	137	; Passo inicial
	.db	1	; Shift inicial
	.db	96	; Altura
	.db	13	; Passo
	.dw	0	; Offset inicial
; Escala 157
	.db	141	; Passo inicial
	.db	1	; Shift inicial
	.db	96	; Altura
	.db	13	; Passo
	.dw	0	; Offset inicial
; Escala 158
	.db	145	; Passo inicial
	.db	1	; Shift inicial
	.db	96	; Altura
	.db	12	; Passo
	.dw	0	; Offset inicial
; Escala 159
	.db	149	; Passo inicial
	.db	1	; Shift inicial
	.db	96	; Altura
	.db	12	; Passo
	.dw	0	; Offset inicial
; Escala 160
	.db	153	; Passo inicial
	.db	1	; Shift inicial
	.db	96	; Altura
	.db	12	; Passo
	.dw	0	; Offset inicial
; Escala 161
	.db	157	; Passo inicial
	.db	1	; Shift inicial
	.db	96	; Altura
	.db	12	; Passo
	.dw	0	; Offset inicial
; Escala 162
	.db	161	; Passo inicial
	.db	1	; Shift inicial
	.db	96	; Altura
	.db	12	; Passo
	.dw	0	; Offset inicial
; Escala 163
	.db	164	; Passo inicial
	.db	1	; Shift inicial
	.db	96	; Altura
	.db	12	; Passo
	.dw	0	; Offset inicial
; Escala 164
	.db	168	; Passo inicial
	.db	1	; Shift inicial
	.db	96	; Altura
	.db	12	; Passo
	.dw	0	; Offset inicial
; Escala 165
	.db	172	; Passo inicial
	.db	1	; Shift inicial
	.db	96	; Altura
	.db	12	; Passo
	.dw	0	; Offset inicial
; Escala 166
	.db	175	; Passo inicial
	.db	1	; Shift inicial
	.db	96	; Altura
	.db	12	; Passo
	.dw	0	; Offset inicial
; Escala 167
	.db	179	; Passo inicial
	.db	1	; Shift inicial
	.db	96	; Altura
	.db	12	; Passo
	.dw	0	; Offset inicial
; Escala 168
	.db	182	; Passo inicial
	.db	1	; Shift inicial
	.db	96	; Altura
	.db	12	; Passo
	.dw	0	; Offset inicial
; Escala 169
	.db	186	; Passo inicial
	.db	1	; Shift inicial
	.db	96	; Altura
	.db	12	; Passo
	.dw	0	; Offset inicial
; Escala 170
	.db	189	; Passo inicial
	.db	1	; Shift inicial
	.db	96	; Altura
	.db	12	; Passo
	.dw	0	; Offset inicial
; Escala 171
	.db	193	; Passo inicial
	.db	1	; Shift inicial
	.db	96	; Altura
	.db	11	; Passo
	.dw	0	; Offset inicial
; Escala 172
	.db	196	; Passo inicial
	.db	1	; Shift inicial
	.db	96	; Altura
	.db	11	; Passo
	.dw	0	; Offset inicial
; Escala 173
	.db	199	; Passo inicial
	.db	1	; Shift inicial
	.db	96	; Altura
	.db	11	; Passo
	.dw	0	; Offset inicial
; Escala 174
	.db	203	; Passo inicial
	.db	1	; Shift inicial
	.db	96	; Altura
	.db	11	; Passo
	.dw	0	; Offset inicial
; Escala 175
	.db	206	; Passo inicial
	.db	1	; Shift inicial
	.db	96	; Altura
	.db	11	; Passo
	.dw	0	; Offset inicial
; Escala 176
	.db	209	; Passo inicial
	.db	1	; Shift inicial
	.db	96	; Altura
	.db	11	; Passo
	.dw	0	; Offset inicial
; Escala 177
	.db	212	; Passo inicial
	.db	1	; Shift inicial
	.db	96	; Altura
	.db	11	; Passo
	.dw	0	; Offset inicial
; Escala 178
	.db	215	; Passo inicial
	.db	1	; Shift inicial
	.db	96	; Altura
	.db	11	; Passo
	.dw	0	; Offset inicial
; Escala 179
	.db	218	; Passo inicial
	.db	1	; Shift inicial
	.db	96	; Altura
	.db	11	; Passo
	.dw	0	; Offset inicial
; Escala 180
	.db	221	; Passo inicial
	.db	1	; Shift inicial
	.db	96	; Altura
	.db	11	; Passo
	.dw	0	; Offset inicial
; Escala 181
	.db	224	; Passo inicial
	.db	1	; Shift inicial
	.db	96	; Altura
	.db	11	; Passo
	.dw	0	; Offset inicial
; Escala 182
	.db	227	; Passo inicial
	.db	1	; Shift inicial
	.db	96	; Altura
	.db	11	; Passo
	.dw	0	; Offset inicial
; Escala 183
	.db	230	; Passo inicial
	.db	1	; Shift inicial
	.db	96	; Altura
	.db	11	; Passo
	.dw	0	; Offset inicial
; Escala 184
	.db	233	; Passo inicial
	.db	1	; Shift inicial
	.db	96	; Altura
	.db	11	; Passo
	.dw	0	; Offset inicial
; Escala 185
	.db	236	; Passo inicial
	.db	1	; Shift inicial
	.db	96	; Altura
	.db	11	; Passo
	.dw	0	; Offset inicial
; Escala 186
	.db	239	; Passo inicial
	.db	1	; Shift inicial
	.db	96	; Altura
	.db	11	; Passo
	.dw	0	; Offset inicial
; Escala 187
	.db	242	; Passo inicial
	.db	1	; Shift inicial
	.db	96	; Altura
	.db	10	; Passo
	.dw	0	; Offset inicial
; Escala 188
	.db	245	; Passo inicial
	.db	1	; Shift inicial
	.db	96	; Altura
	.db	10	; Passo
	.dw	0	; Offset inicial
; Escala 189
	.db	247	; Passo inicial
	.db	1	; Shift inicial
	.db	96	; Altura
	.db	10	; Passo
	.dw	0	; Offset inicial
; Escala 190
	.db	250	; Passo inicial
	.db	1	; Shift inicial
	.db	96	; Altura
	.db	10	; Passo
	.dw	0	; Offset inicial
; Escala 191
	.db	253	; Passo inicial
	.db	1	; Shift inicial
	.db	96	; Altura
	.db	10	; Passo
	.dw	0	; Offset inicial
; Escala 192
	.db	0	; Passo inicial
	.db	2	; Shift inicial
	.db	96	; Altura
	.db	10	; Passo
	.dw	0	; Offset inicial
