	.data
	.globl	__intro3_pal
__intro3_pal:
	.dc.w	0
	.dc.w	2
	.dc.w	4
	.dc.w	6
	.dc.w	8
	.dc.w	10
	.dc.w	1092
	.dc.w	1670
	.dc.w	12
	.dc.w	12
	.dc.w	14
	.dc.w	78
	.dc.w	142
	.dc.w	174
	.dc.w	206
	.dc.w	3276
	.globl	__intro4_pal
__intro4_pal:
	.dc.w	0
	.dc.w	0
	.dc.w	546
	.dc.w	546
	.dc.w	546
	.dc.w	546
	.dc.w	1092
	.dc.w	1092
	.dc.w	1092
	.dc.w	1638
	.dc.w	1638
	.dc.w	14
	.dc.w	238
	.dc.w	3822
	.dc.w	3822
	.dc.w	3822
	.globl	__intro5_pal
__intro5_pal:
	.dc.w	0
	.dc.w	0
	.dc.w	0
	.dc.w	1024
	.dc.w	66
	.dc.w	2114
	.dc.w	162
	.dc.w	224
	.dc.w	550
	.dc.w	584
	.dc.w	618
	.dc.w	684
	.dc.w	1638
	.dc.w	1612
	.dc.w	2150
	.dc.w	2732
	.globl	__select_pal
__select_pal:
	.dc.w	0
	.dc.w	32
	.dc.w	34
	.dc.w	2082
	.dc.w	610
	.dc.w	674
	.dc.w	3138
	.dc.w	2120
	.dc.w	584
	.dc.w	1100
	.dc.w	684
	.dc.w	750
	.dc.w	1638
	.dc.w	2122
	.dc.w	2150
	.dc.w	2732
	.globl	__select0_pal
__select0_pal:
	.dc.w	0
	.dc.w	0
	.dc.w	0
	.dc.w	0
	.dc.w	1026
	.dc.w	1570
	.dc.w	2082
	.dc.w	3808
	.dc.w	552
	.dc.w	1100
	.dc.w	1100
	.dc.w	1134
	.dc.w	2628
	.dc.w	3140
	.dc.w	3140
	.dc.w	3208
	.globl	__spewm_pal
__spewm_pal:
	.dc.w	2
	.dc.w	546
	.dc.w	546
	.dc.w	546
	.dc.w	6
	.dc.w	6
	.dc.w	4
	.dc.w	516
	.dc.w	8
	.dc.w	8
	.dc.w	8
	.dc.w	8
	.dc.w	8
	.dc.w	10
	.dc.w	10
	.dc.w	10
	.globl	__spews_pal
__spews_pal:
	.dc.w	2182
	.dc.w	2662
	.dc.w	3138
	.dc.w	3174
	.dc.w	3650
	.dc.w	3650
	.dc.w	3684
	.dc.w	3684
	.dc.w	2184
	.dc.w	2728
	.dc.w	2730
	.dc.w	3276
	.dc.w	3208
	.dc.w	3240
	.dc.w	3242
	.dc.w	3276
	.globl	__table2_pal
__table2_pal:
	.dc.w	0
	.dc.w	0
	.dc.w	0
	.dc.w	0
	.dc.w	546
	.dc.w	1570
	.dc.w	2116
	.dc.w	2116
	.dc.w	1094
	.dc.w	1640
	.dc.w	2150
	.dc.w	2186
	.dc.w	2186
	.dc.w	2730
	.dc.w	2732
	.dc.w	3278
	.globl	__taunt_pal
__taunt_pal:
	.dc.w	0
	.dc.w	0
	.dc.w	0
	.dc.w	0
	.dc.w	0
	.dc.w	0
	.dc.w	0
	.dc.w	512
	.dc.w	514
	.dc.w	546
	.dc.w	546
	.dc.w	546
	.dc.w	1060
	.dc.w	1094
	.dc.w	1606
	.dc.w	2154
	.globl	__tauntb_pal
__tauntb_pal:
	.dc.w	0
	.dc.w	0
	.dc.w	0
	.dc.w	0
	.dc.w	0
	.dc.w	0
	.dc.w	0
	.dc.w	512
	.dc.w	2
	.dc.w	514
	.dc.w	546
	.dc.w	546
	.dc.w	548
	.dc.w	1092
	.dc.w	1606
	.dc.w	2730
	.globl	__winner1_pal
__winner1_pal:
	.dc.w	0
	.dc.w	0
	.dc.w	0
	.dc.w	0
	.dc.w	512
	.dc.w	512
	.dc.w	1024
	.dc.w	1056
	.dc.w	2082
	.dc.w	2628
	.dc.w	3140
	.dc.w	3140
	.dc.w	3140
	.dc.w	3686
	.dc.w	3788
	.dc.w	3822
	.globl	__winner2_pal
__winner2_pal:
	.dc.w	0
	.dc.w	0
	.dc.w	0
	.dc.w	32
	.dc.w	32
	.dc.w	32
	.dc.w	64
	.dc.w	576
	.dc.w	642
	.dc.w	1188
	.dc.w	1220
	.dc.w	1766
	.dc.w	1766
	.dc.w	2280
	.dc.w	3308
	.dc.w	3308
	.globl	__winner3_pal
__winner3_pal:
	.dc.w	0
	.dc.w	0
	.dc.w	0
	.dc.w	2
	.dc.w	2
	.dc.w	2
	.dc.w	4
	.dc.w	548
	.dc.w	550
	.dc.w	1098
	.dc.w	1100
	.dc.w	1102
	.dc.w	1102
	.dc.w	1102
	.dc.w	2190
	.dc.w	3822
	.globl	__winner4_pal
__winner4_pal:
	.dc.w	0
	.dc.w	0
	.dc.w	0
	.dc.w	0
	.dc.w	512
	.dc.w	514
	.dc.w	546
	.dc.w	1058
	.dc.w	1604
	.dc.w	2664
	.dc.w	3178
	.dc.w	3210
	.dc.w	3210
	.dc.w	3724
	.dc.w	3756
	.dc.w	3822
	.globl	__winner5_pal
__winner5_pal:
	.dc.w	0
	.dc.w	0
	.dc.w	0
	.dc.w	0
	.dc.w	34
	.dc.w	34
	.dc.w	68
	.dc.w	614
	.dc.w	648
	.dc.w	1194
	.dc.w	1228
	.dc.w	1262
	.dc.w	1774
	.dc.w	2286
	.dc.w	2798
	.dc.w	3310
	.globl	__zone1_pal
__zone1_pal:
	.dc.w	512
	.dc.w	1024
	.dc.w	1536
	.dc.w	2048
	.dc.w	2560
	.dc.w	2560
	.dc.w	3072
	.dc.w	3584
	.dc.w	1572
	.dc.w	1130
	.dc.w	3174
	.dc.w	3118
	.dc.w	716
	.dc.w	2762
	.dc.w	3242
	.dc.w	3822
	.globl	__zone2_pal
__zone2_pal:
	.dc.w	0
	.dc.w	0
	.dc.w	546
	.dc.w	546
	.dc.w	546
	.dc.w	546
	.dc.w	1092
	.dc.w	1092
	.dc.w	1092
	.dc.w	1092
	.dc.w	1638
	.dc.w	1638
	.dc.w	1638
	.dc.w	1638
	.dc.w	2184
	.dc.w	2184
	.globl	__zone2S_pal
__zone2S_pal:
	.dc.w	0
	.dc.w	0
	.dc.w	0
	.dc.w	0
	.dc.w	512
	.dc.w	1024
	.dc.w	1024
	.dc.w	1024
	.dc.w	512
	.dc.w	514
	.dc.w	1024
	.dc.w	1058
	.dc.w	4
	.dc.w	1092
	.dc.w	10
	.dc.w	1638
	.globl	__zone3_pal
__zone3_pal:
	.dc.w	674
	.dc.w	674
	.dc.w	674
	.dc.w	674
	.dc.w	674
	.dc.w	1220
	.dc.w	1700
	.dc.w	1220
	.dc.w	2182
	.dc.w	2184
	.dc.w	1734
	.dc.w	2760
	.dc.w	2730
	.dc.w	2730
	.dc.w	2794
	.dc.w	3308
	.globl	__zone3S_pal
__zone3S_pal:
	.dc.w	674
	.dc.w	674
	.dc.w	1188
	.dc.w	1188
	.dc.w	1188
	.dc.w	1668
	.dc.w	1188
	.dc.w	1220
	.dc.w	2214
	.dc.w	1734
	.dc.w	1734
	.dc.w	2248
	.dc.w	2730
	.dc.w	2762
	.dc.w	3276
	.dc.w	3822
	.globl	__zone4_pal
__zone4_pal:
	.dc.w	2
	.dc.w	1092
	.dc.w	1092
	.dc.w	1092
	.dc.w	1092
	.dc.w	552
	.dc.w	1160
	.dc.w	2184
	.dc.w	238
	.dc.w	716
	.dc.w	2730
	.dc.w	3276
	.dc.w	3276
	.dc.w	3822
	.dc.w	3822
	.dc.w	3822
	.globl	__zone5_pal
__zone5_pal:
	.dc.w	1056
	.dc.w	3138
	.dc.w	3650
	.dc.w	3684
	.dc.w	162
	.dc.w	3684
	.dc.w	3716
	.dc.w	3718
	.dc.w	3116
	.dc.w	3598
	.dc.w	3718
	.dc.w	3750
	.dc.w	204
	.dc.w	3784
	.dc.w	3786
	.dc.w	3822
	.globl	__zone6_pal
__zone6_pal:
	.dc.w	0
	.dc.w	546
	.dc.w	546
	.dc.w	1092
	.dc.w	1092
	.dc.w	1638
	.dc.w	1638
	.dc.w	1638
	.dc.w	1638
	.dc.w	2150
	.dc.w	3138
	.dc.w	3140
	.dc.w	2184
	.dc.w	2184
	.dc.w	2728
	.dc.w	2730
	.globl	__zone7_pal
__zone7_pal:
	.dc.w	0
	.dc.w	0
	.dc.w	0
	.dc.w	0
	.dc.w	546
	.dc.w	546
	.dc.w	1092
	.dc.w	1092
	.dc.w	4
	.dc.w	1092
	.dc.w	1638
	.dc.w	552
	.dc.w	1638
	.dc.w	2184
	.dc.w	2184
	.dc.w	3276
	.globl	__zone8_pal
__zone8_pal:
	.dc.w	3138
	.dc.w	3276
	.dc.w	3822
	.dc.w	3822
	.dc.w	3822
	.dc.w	3822
	.dc.w	3822
	.dc.w	3822
	.dc.w	3822
	.dc.w	3822
	.dc.w	3822
	.dc.w	3822
	.dc.w	3822
	.dc.w	3822
	.dc.w	3822
	.dc.w	3822
	.globl	__taunta_pal
__taunta_pal:
	.dc.w	0
	.dc.w	3822
	.dc.w	3822
	.dc.w	3822
	.dc.w	3822
	.dc.w	3822
	.dc.w	3822
	.dc.w	3822
	.dc.w	3822
	.dc.w	3822
	.dc.w	3822
	.dc.w	3822
	.dc.w	3822
	.dc.w	3822
	.dc.w	3822
	.dc.w	3808
	.globl	__redbio_pal
__redbio_pal:
	.dc.w	0
	.dc.w	2
	.dc.w	548
	.dc.w	1092
	.dc.w	548
	.dc.w	1092
	.dc.w	1092
	.dc.w	1638
	.dc.w	550
	.dc.w	1098
	.dc.w	1640
	.dc.w	170
	.dc.w	1638
	.dc.w	1638
	.dc.w	2188
	.dc.w	3278
	.globl	__greenbio_pal
__greenbio_pal:
	.dc.w	0
	.dc.w	32
	.dc.w	548
	.dc.w	580
	.dc.w	578
	.dc.w	1092
	.dc.w	642
	.dc.w	1220
	.dc.w	1094
	.dc.w	1094
	.dc.w	1702
	.dc.w	682
	.dc.w	1638
	.dc.w	1702
	.dc.w	2762
	.dc.w	3822
	.globl	__bluebio_pal
__bluebio_pal:
	.dc.w	0
	.dc.w	0
	.dc.w	512
	.dc.w	546
	.dc.w	1058
	.dc.w	1092
	.dc.w	1604
	.dc.w	3140
	.dc.w	1092
	.dc.w	1604
	.dc.w	1126
	.dc.w	682
	.dc.w	2150
	.dc.w	2662
	.dc.w	2762
	.dc.w	3822
	.globl	__yellbio_pal
__yellbio_pal:
	.dc.w	0
	.dc.w	0
	.dc.w	580
	.dc.w	1092
	.dc.w	580
	.dc.w	1092
	.dc.w	1092
	.dc.w	1638
	.dc.w	614
	.dc.w	1638
	.dc.w	1194
	.dc.w	1262
	.dc.w	2184
	.dc.w	2286
	.dc.w	3310
	.dc.w	3822
	.globl	__purpbio_pal
__purpbio_pal:
	.dc.w	0
	.dc.w	514
	.dc.w	1060
	.dc.w	1092
	.dc.w	1604
	.dc.w	1092
	.dc.w	1092
	.dc.w	1638
	.dc.w	1606
	.dc.w	2118
	.dc.w	1638
	.dc.w	682
	.dc.w	2664
	.dc.w	3178
	.dc.w	3244
	.dc.w	3822
	.globl	_backgrounds
_backgrounds:
	.dc.l	L0
	.dc.l	L1
	.dc.l	__intro3_pal
	.dc.l	L2
	.dc.l	L3
	.dc.l	__intro4_pal
	.dc.l	L4
	.dc.l	L5
	.dc.l	__intro5_pal
	.dc.l	L6
	.dc.l	L7
	.dc.l	__select_pal
	.dc.l	L8
	.dc.l	L9
	.dc.l	__select0_pal
	.dc.l	L10
	.dc.l	L11
	.dc.l	__spewm_pal
	.dc.l	L12
	.dc.l	L13
	.dc.l	__spews_pal
	.dc.l	L14
	.dc.l	L15
	.dc.l	__table2_pal
	.dc.l	L16
	.dc.l	L17
	.dc.l	__taunt_pal
	.dc.l	L18
	.dc.l	L19
	.dc.l	__taunta_pal
	.dc.l	L20
	.dc.l	L21
	.dc.l	__tauntb_pal
	.dc.l	L22
	.dc.l	L23
	.dc.l	__winner1_pal
	.dc.l	L24
	.dc.l	L25
	.dc.l	__winner2_pal
	.dc.l	L26
	.dc.l	L27
	.dc.l	__winner3_pal
	.dc.l	L28
	.dc.l	L29
	.dc.l	__winner4_pal
	.dc.l	L30
	.dc.l	L31
	.dc.l	__winner5_pal
	.dc.l	L32
	.dc.l	L33
	.dc.l	__zone1_pal
	.dc.l	L34
	.dc.l	L35
	.dc.l	__zone2_pal
	.dc.l	L36
	.dc.l	L37
	.dc.l	__zone2S_pal
	.dc.l	L38
	.dc.l	L39
	.dc.l	__zone3_pal
	.dc.l	L40
	.dc.l	L41
	.dc.l	__zone3S_pal
	.dc.l	L42
	.dc.l	L43
	.dc.l	__zone4_pal
	.dc.l	L44
	.dc.l	L45
	.dc.l	__zone5_pal
	.dc.l	L46
	.dc.l	L47
	.dc.l	__zone6_pal
	.dc.l	L48
	.dc.l	L49
	.dc.l	__zone7_pal
	.dc.l	L50
	.dc.l	L51
	.dc.l	__zone8_pal
	.dc.l	L52
	.dc.l	L53
	.dc.l	__redbio_pal
	.dc.l	L54
	.dc.l	L55
	.dc.l	__bluebio_pal
	.dc.l	L56
	.dc.l	L57
	.dc.l	__yellbio_pal
	.dc.l	L58
	.dc.l	L59
	.dc.l	__greenbio_pal
	.dc.l	L60
	.dc.l	L61
	.dc.l	__purpbio_pal
	.bss
	.globl	_curr_bkg
	.comm	_curr_bkg,4
	.globl	_huge_buffer
	.comm	_huge_buffer,35840
	.data
L61:	.dc.b	$50,$55,$52,$50,$42,$49,$4f,$2e,$4d,$41,$50
	.dc.b	0
L60:	.dc.b	$50,$55,$52,$50,$42,$49,$4f,$2e,$52,$44,$43
	.dc.b	0
L59:	.dc.b	$47,$52,$45,$45,$4e,$42,$49,$4f,$2e,$4d,$41
	.dc.b	$50
	.dc.b	0
L58:	.dc.b	$47,$52,$45,$45,$4e,$42,$49,$4f,$2e,$52,$44
	.dc.b	$43
	.dc.b	0
L57:	.dc.b	$59,$45,$4c,$4c,$42,$49,$4f,$2e,$4d,$41,$50
	.dc.b	0
L56:	.dc.b	$59,$45,$4c,$4c,$42,$49,$4f,$2e,$52,$44,$43
	.dc.b	0
L55:	.dc.b	$42,$4c,$55,$45,$42,$49,$4f,$2e,$4d,$41,$50
	.dc.b	0
L54:	.dc.b	$42,$4c,$55,$45,$42,$49,$4f,$2e,$52,$44,$43
	.dc.b	0
L53:	.dc.b	$52,$45,$44,$42,$49,$4f,$2e,$4d,$41,$50
	.dc.b	0
L52:	.dc.b	$52,$45,$44,$42,$49,$4f,$2e,$52,$44,$43
	.dc.b	0
L51:	.dc.b	$5a,$4f,$4e,$45,$38,$2e,$4d,$41,$50
	.dc.b	0
L50:	.dc.b	$5a,$4f,$4e,$45,$38,$2e,$52,$44,$43
	.dc.b	0
L49:	.dc.b	$5a,$4f,$4e,$45,$37,$2e,$4d,$41,$50
	.dc.b	0
L48:	.dc.b	$5a,$4f,$4e,$45,$37,$2e,$52,$44,$43
	.dc.b	0
L47:	.dc.b	$5a,$4f,$4e,$45,$36,$2e,$4d,$41,$50
	.dc.b	0
L46:	.dc.b	$5a,$4f,$4e,$45,$36,$2e,$52,$44,$43
	.dc.b	0
L45:	.dc.b	$5a,$4f,$4e,$45,$35,$2e,$4d,$41,$50
	.dc.b	0
L44:	.dc.b	$5a,$4f,$4e,$45,$35,$2e,$52,$44,$43
	.dc.b	0
L43:	.dc.b	$5a,$4f,$4e,$45,$34,$2e,$4d,$41,$50
	.dc.b	0
L42:	.dc.b	$5a,$4f,$4e,$45,$34,$2e,$52,$44,$43
	.dc.b	0
L41:	.dc.b	$5a,$4f,$4e,$45,$33,$53,$2e,$4d,$41,$50
	.dc.b	0
L40:	.dc.b	$5a,$4f,$4e,$45,$33,$53,$2e,$52,$44,$43
	.dc.b	0
L39:	.dc.b	$5a,$4f,$4e,$45,$33,$2e,$4d,$41,$50
	.dc.b	0
L38:	.dc.b	$5a,$4f,$4e,$45,$33,$2e,$52,$44,$43
	.dc.b	0
L37:	.dc.b	$5a,$4f,$4e,$45,$32,$53,$2e,$4d,$41,$50
	.dc.b	0
L36:	.dc.b	$5a,$4f,$4e,$45,$32,$53,$2e,$52,$44,$43
	.dc.b	0
L35:	.dc.b	$5a,$4f,$4e,$45,$32,$2e,$4d,$41,$50
	.dc.b	0
L34:	.dc.b	$5a,$4f,$4e,$45,$32,$2e,$52,$44,$43
	.dc.b	0
L33:	.dc.b	$5a,$4f,$4e,$45,$31,$2e,$4d,$41,$50
	.dc.b	0
L32:	.dc.b	$5a,$4f,$4e,$45,$31,$2e,$52,$44,$43
	.dc.b	0
L31:	.dc.b	$57,$49,$4e,$4e,$45,$52,$35,$2e,$4d,$41,$50
	.dc.b	0
L30:	.dc.b	$57,$49,$4e,$4e,$45,$52,$35,$2e,$52,$44,$43
	.dc.b	0
L29:	.dc.b	$57,$49,$4e,$4e,$45,$52,$34,$2e,$4d,$41,$50
	.dc.b	0
L28:	.dc.b	$57,$49,$4e,$4e,$45,$52,$34,$2e,$52,$44,$43
	.dc.b	0
L27:	.dc.b	$57,$49,$4e,$4e,$45,$52,$33,$2e,$4d,$41,$50
	.dc.b	0
L26:	.dc.b	$57,$49,$4e,$4e,$45,$52,$33,$2e,$52,$44,$43
	.dc.b	0
L25:	.dc.b	$57,$49,$4e,$4e,$45,$52,$32,$2e,$4d,$41,$50
	.dc.b	0
L24:	.dc.b	$57,$49,$4e,$4e,$45,$52,$32,$2e,$52,$44,$43
	.dc.b	0
L23:	.dc.b	$57,$49,$4e,$4e,$45,$52,$31,$2e,$4d,$41,$50
	.dc.b	0
L22:	.dc.b	$57,$49,$4e,$4e,$45,$52,$31,$2e,$52,$44,$43
	.dc.b	0
L21:	.dc.b	$54,$41,$55,$4e,$54,$42,$2e,$4d,$41,$50
	.dc.b	0
L20:	.dc.b	$54,$41,$55,$4e,$54,$42,$2e,$52,$44,$43
	.dc.b	0
L19:	.dc.b	$54,$41,$55,$4e,$54,$41,$2e,$4d,$41,$50
	.dc.b	0
L18:	.dc.b	$54,$41,$55,$4e,$54,$41,$2e,$52,$44,$43
	.dc.b	0
L17:	.dc.b	$54,$41,$55,$4e,$54,$2e,$4d,$41,$50
	.dc.b	0
L16:	.dc.b	$54,$41,$55,$4e,$54,$2e,$52,$44,$43
	.dc.b	0
L15:	.dc.b	$54,$41,$42,$4c,$45,$32,$2e,$4d,$41,$50
	.dc.b	0
L14:	.dc.b	$54,$41,$42,$4c,$45,$32,$2e,$52,$44,$43
	.dc.b	0
L13:	.dc.b	$53,$50,$45,$57,$53,$2e,$4d,$41,$50
	.dc.b	0
L12:	.dc.b	$53,$50,$45,$57,$53,$2e,$52,$44,$43
	.dc.b	0
L11:	.dc.b	$53,$50,$45,$57,$4d,$2e,$4d,$41,$50
	.dc.b	0
L10:	.dc.b	$53,$50,$45,$57,$4d,$2e,$52,$44,$43
	.dc.b	0
L9:	.dc.b	$53,$45,$4c,$45,$43,$54,$30,$2e,$4d,$41,$50
	.dc.b	0
L8:	.dc.b	$53,$45,$4c,$45,$43,$54,$30,$2e,$52,$44,$43
	.dc.b	0
L7:	.dc.b	$53,$45,$4c,$45,$43,$54,$2e,$4d,$41,$50
	.dc.b	0
L6:	.dc.b	$53,$45,$4c,$45,$43,$54,$2e,$52,$44,$43
	.dc.b	0
L5:	.dc.b	$49,$4e,$54,$52,$4f,$35,$2e,$4d,$41,$50
	.dc.b	0
L4:	.dc.b	$49,$4e,$54,$52,$4f,$35,$2e,$52,$44,$43
	.dc.b	0
L3:	.dc.b	$49,$4e,$54,$52,$4f,$34,$2e,$4d,$41,$50
	.dc.b	0
L2:	.dc.b	$49,$4e,$54,$52,$4f,$34,$2e,$52,$44,$43
	.dc.b	0
L1:	.dc.b	$49,$4e,$54,$52,$4f,$33,$2e,$4d,$41,$50
	.dc.b	0
L0:	.dc.b	$49,$4e,$54,$52,$4f,$33,$2e,$52,$44,$43
	.dc.b	0
	.text
	.globl	_load_bkgnd
_load_bkgnd:
	link	a6,#-4
	moveq.l	#12,d0
	mulu	8(a6),d0
	moveq.l	#0,d1
	move.w	d0,d1
	add.l	#_backgrounds,d1
	move.l	d1,a0
	move.l	d1,_curr_bkg
	move.l	(a0),-(sp)
	pea	-4(a6)
	jsr	_get_GFS_fileaddr
	addq.w	#8,sp
	move.l	#_huge_buffer,-(sp)
	move.l	-4(a6),-(sp)
	jsr	_RDC_Decompress
	addq.w	#8,sp
	move.l	#_huge_buffer,-(sp)
	move.w	#1120,-(sp)
	move.w	#256,-(sp)
	jsr	_set_bkg_data
	addq.w	#8,sp
	move.l	_curr_bkg,a0
	move.l	4(a0),-(sp)
	pea	-4(a6)
	jsr	_get_GFS_fileaddr
	addq.w	#8,sp
	move.w	#256,-(sp)
	move.w	#57344,-(sp)
	move.l	-4(a6),-(sp)
	move.w	#28,-(sp)
	move.w	#40,-(sp)
	clr.w	-(sp)
	clr.w	-(sp)
	jsr	_set_bkg_tiles
	lea	16(sp),sp
	move.l	_curr_bkg,a0
	move.l	8(a0),-(sp)
	clr.w	-(sp)
	jsr	_set_colors
	unlk	a6
	rts
