.SUFFIXES : .x .o .c .s

CC=hcc
TOP=top
AS=jas
LD=ld
RM=del
GFS=..\utils\applygfs
INC= -I..\\..\\include\\


all     : prog

prog: pongkomb.o bkgs.o \
sega.o genesis.o utils.o psgsound.o interr.o gfs.o rdc.o \
rpgwalk.o conio.o string.o plee.o font.o genesisb.o
	$(LD) -b -g -v -o pongkomb.bin -f objet.inc
	$(GFS) pongkomb.bin 262144 gamedata.gfs

clean:
	$(RM) *.o
	$(RM) test.s
	$(RM) test.bin
	$(RM) *.bak

.c.o: 
	@-echo "Making component -> $*.o"
	$(CC) $(INC) $<
	$(TOP) $*.s
	$(AS) $*.s

.s.o:
	@-echo "Making component -> $*.o"
	$(AS) $(CDIR)$*.s


# dependencies -- DO NOT DELETE BELOW THIS LINE -- make depends on it.

pongkomb.o: pongkomb.c
bkgs.o	  : bkgs.c
sega.o    : sega.s
genesis.o :	genesis.c
genesisb.o:	genesisb.c
conio.o   :	conio.c
string.o  :	string.c
pleee.o   :	plee.c
utils.o   :	utils.c
psgsound.o:	psgsound.c
interr.o  :	interr.c
gfs.o  	  :	gfs.c
rdc.o  	  :	rdc.c
rpgwalk.o :	rpgwalk.c
font.o    : font.c