pcx2gen pcx2gen\title.pcx title.til
move title.h ..\titlepal.h

pcx2gen pcx2gen\smaltitl.pcx smaltitl.til
move smaltitl.h ..\smaltitl.h

pcx2gen pcx2gen\back.pcx back.til
move back.h ..\titlback.h

pcx2gen pcx2gen\brflag.pcx brflag.til
move brflag.h ..\brflag.h

pcx2gen pcx2gen\usflag.pcx usflag.til
move usflag.h ..\usflag.h

pcx2gen pcx2gen\1p.pcx _1p.til
move _1p.h ..\1p_icn.h

pcx2gen pcx2gen\2p.pcx _2p.til
move _2p.h ..\2p_icn.h

pcx2gen pcx2gen\winner.pcx winner.til
move winner.h ..\winner.h

pcx2gen pcx2gen\loser.pcx loser.til
move loser.h ..\loser.h

pcx2gen pcx2gen\venc.pcx venc.til
move venc.h ..\venc.h

pcx2gen pcx2gen\perd.pcx perd.til
move perd.h ..\perd.h

