# Project: memload_test
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = 
OBJ  = ../../../lib/chs_load.o ../../../lib/chs_func.o ../../../lib/chs_intr.o ../../../lib/stdio/chs_cons.o ../cheese_memload.o ../../../lib/chs_fnci.o ../../../lib/curses/chs_itfc.o $(RES)
LINKOBJ  = ../../../lib/chs_load.o ../../../lib/chs_func.o ../../../lib/chs_intr.o ../../../lib/stdio/chs_cons.o ../cheese_memload.o ../../../lib/chs_fnci.o ../../../lib/curses/chs_itfc.o $(RES)
LIBS =  -L"C:/Dev-Cpp/lib"  
INCS =  -I"C:/Dev-Cpp/include"  -I"../../../../include"  -I"../../../../include/win32" 
CXXINCS =  -I"C:/Dev-Cpp/lib/gcc/mingw32/3.4.2/include"  -I"C:/Dev-Cpp/include/c++/3.4.2/backward"  -I"C:/Dev-Cpp/include/c++/3.4.2/mingw32"  -I"C:/Dev-Cpp/include/c++/3.4.2"  -I"C:/Dev-Cpp/include"  -I"../../../../include"  -I"../../../../include/win32" 
BIN  = memload_test.exe
CXXFLAGS = $(CXXINCS)  
CFLAGS = $(INCS)  
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before memload_test.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o "memload_test.exe" $(LIBS)

../../../lib/chs_load.o: ../../../lib/chs_load.c
	$(CC) -c ../../../lib/chs_load.c -o ../../../lib/chs_load.o $(CFLAGS)

../../../lib/chs_func.o: ../../../lib/chs_func.c
	$(CC) -c ../../../lib/chs_func.c -o ../../../lib/chs_func.o $(CFLAGS)

../../../lib/chs_intr.o: ../../../lib/chs_intr.c
	$(CC) -c ../../../lib/chs_intr.c -o ../../../lib/chs_intr.o $(CFLAGS)

../../../lib/stdio/chs_cons.o: ../../../lib/stdio/chs_cons.c
	$(CC) -c ../../../lib/stdio/chs_cons.c -o ../../../lib/stdio/chs_cons.o $(CFLAGS)

../cheese_memload.o: ../cheese_memload.c
	$(CC) -c ../cheese_memload.c -o ../cheese_memload.o $(CFLAGS)

../../../lib/chs_fnci.o: ../../../lib/chs_fnci.c
	$(CC) -c ../../../lib/chs_fnci.c -o ../../../lib/chs_fnci.o $(CFLAGS)

../../../lib/curses/chs_itfc.o: ../../../lib/curses/chs_itfc.c
	$(CC) -c ../../../lib/curses/chs_itfc.c -o ../../../lib/curses/chs_itfc.o $(CFLAGS)
